#!/bin/bash -e
### BEGIN INIT INFO
# Provides:          firewall-iptables
# Required-Start:    networking network-manager
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: very basic iptables firewall, and port forwarding setup.
# Description: Mostly copied from David A. Ranch (http://www.ecst.csuchico.edu/~dranch). Rewritten here as an debian Linux init script.
#              You'll probably have to edit default port list, and interface names.
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="Basic iptables firewall"
NAME=firewall-iptables
DAEMON=/usr/sbin/$NAME
DAEMON_ARGS="--options args"
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME
CONFFILE=/etc/default/"$NAME"
# Default ports.
INBOUND_TCP_ALLOW=""
INBOUND_UDP_ALLOW=""
FIREWALL_DEFAULT_REJECT=""
FIREWALL_INPUT_DROP=""

# Check that networking is up.
[[ "${NETWORKING}" = "no" ]] && exit 0
# Read configuration variable file if it is present.
[ -r "$CONFFILE" ] && . "$CONFFILE"
# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh
# Define LSB log_* functions. Depend on lsb-base (>= 3.2-14) to ensure that this file is present and status_of_proc is working.
. /lib/lsb/init-functions

function set_firewall_rules()
{
  clear_firewall_chains
  # Firewall. Add our chains so we can modularize.
  iptables -t filter -N gw_firewall_filter_input
  iptables -A gw_firewall_filter_input -m comment --comment "firewall-iptables firewall rules"
  # We can talk to ourselves freely. Allow all outgoing connections we start.
  # Allowing ssh, http, https, vnc - youll have to come and edit this as your firewall rules!
  iptables -A gw_firewall_filter_input -i lo -j ACCEPT
  iptables -A gw_firewall_filter_input -p icmp -j ACCEPT
  iptables -A gw_firewall_filter_input -m state --state RELATED,ESTABLISHED -j ACCEPT
  # iptables -A INPUT -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT
  [[ -n $INBOUND_TCP_ALLOW ]] && iptables -A gw_firewall_filter_input -p tcp -m multiport --destination-port $INBOUND_TCP_ALLOW -j ACCEPT
  [[ -n $INBOUND_UDP_ALLOW ]] && iptables -A gw_firewall_filter_input -p udp -m multiport --destination-port $INBOUND_UDP_ALLOW -j ACCEPT
  #iptables -A INPUT -j LOG
  [[ -n "FIREWALL_DEFAULT_REJECT" ]] && iptables -A gw_firewall_filter_input -j REJECT
  [[ -n "FIREWALL_INPUT_DROP" ]] && iptables -P INPUT DROP # Problem is can't restore this.
  iptables -A INPUT -j gw_firewall_filter_input
}

function clear_firewall_chains()
{
  if chain_exists filter gw_firewall_filter_input; then
    iptables -t filter -D INPUT -j gw_firewall_filter_input
    iptables -t filter -F gw_firewall_filter_input
    iptables -t filter -X gw_firewall_filter_input
  fi
  [[ -n "FIREWALL_INPUT_DROP" ]] && iptables -P INPUT ACCEPT # Problem is may not have been this.
}

function chain_exists()
{
  if [[ -n `iptables -t "$1" --list "$2" 2>/dev/null` ]]; then
    return 0
  fi
  return 1
}

function do_start()
{
  echo "Starting simple firewall-iptables."
  set_firewall_rules
  echo -n "Started firewall-iptables."
  success
  echo
  return 0
}

function do_stop()
{
  echo "Stopping firewall-iptables."
  clear_firewall_chains
  echo -n "Stopped firewall-iptables."
  success
  echo
  return 0
}

function do_restart()
{
  $0 stop
  $0 start
  return $?
}

function do_status()
{
  $IPTABLES -L
  return 0
}

function success()
{
  echo -n ""
}

function do_run()
{
  case "$1" in
    start)
      [ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
      do_start
      case "$?" in
        0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
        2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
      esac
    ;;
    stop)
      [ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
      do_stop
      case "$?" in
        0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
        2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
      esac
    ;;
    restart|force-reload)
      # If the "reload" option is implemented then remove the
      # 'force-reload' alias
      log_daemon_msg "Restarting $DESC" "$NAME"
      do_stop
      case "$?" in
        0|1)
          do_start
          case "$?" in
            0) log_end_msg 0 ;;
            1) log_end_msg 1 ;; # Old process is still running
            *) log_end_msg 1 ;; # Failed to start
          esac
        ;;
        *)
          # Failed to stop
        log_end_msg 1
        ;;
      esac
    ;;
    *)
      #echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
      echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload}" >&2
      exit 3
    ;;
  esac
  return 0;
}

do_run "$@"
exit 0;
