#!/bin/bash -e
[ -r "$FIREWALL_CONFFILE" ] && . "$FIREWALL_CONFFILE"
INBOUND_TCP_PORT_ALLOW=${INBOUND_TCP_PORT_ALLOW:-""}
INBOUND_UDP_PORT_ALLOW=${INBOUND_UDP_PORT_ALLOW:-""}
FIREWALL_LOG_REJECT=${FIREWALL_LOG_REJECT:-""}
FIREWALL_INPUT_DEFAULT_RULE=${FIREWALL_REJECT_RULE:-"REJECT"}

function do_start()
{
  do_stop
  # Firewall. Add a chain so we can keep it modular.
  iptables -t filter -N firewall_input_port_filter
  iptables -A firewall_input_port_filter -m comment --comment "firewall-iptables firewall input port rules"
  iptables -A INPUT -j firewall_input_port_filter
  iptables -A firewall_input_port_filter -i lo -j RETURN # We can talk to ourselves freely.
  iptables -A firewall_input_port_filter -p icmp -j RETURN # TODO: filter.
  iptables -A firewall_input_port_filter -m state --state RELATED,ESTABLISHED -j RETURN # Allow all outgoing connections we start.
  [[ -n ${INBOUND_TCP_PORT_ALLOW// /,} ]] && iptables -A firewall_input_port_filter -p tcp -m multiport --destination-port ${INBOUND_TCP_PORT_ALLOW// /,} -j RETURN
  [[ -n ${INBOUND_UDP_PORT_ALLOW// /,} ]] && iptables -A firewall_input_port_filter -p udp -m multiport --destination-port ${INBOUND_UDP_PORT_ALLOW// /,} -j RETURN
  [[ -n "${FIREWALL_LOG_REJECT}" ]] && iptables -A firewall_input_port_filter -j LOG --log-prefix="firewall-iptables REJECTED "
  iptables -A firewall_input_port_filter -j "${FIREWALL_INPUT_DEFAULT_RULE}"
}

function do_stop()
{
  if chain_exists filter firewall_input_port_filter; then
    iptables -t filter -D INPUT -j firewall_input_port_filter
    iptables -t filter -F firewall_input_port_filter
    iptables -t filter -X firewall_input_port_filter
  fi
  iptables -P INPUT ACCEPT
}

function chain_exists()
{
  iptables -t "$1" -n --list "$2" >/dev/null 2>&1
  return $?
}

[[ -z "$1" || ( "$1" != "start" && "$1" != "stop" ) ]] && exit 1;

case "$1" in
  start)
    do_start
  ;;
  stop)
    do_stop
  ;;
esac
